=== Choinek/magento2-alexa/app/code/AlanKent/Alexa/etc/alexa/alexa_listeners.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alexaListener" type="alexaListenerType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="name">
            <xs:annotation>
                <xs:documentation>
                    Alexa Listener name should be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="alexaListener"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="alexaListenerType">
        <xs:sequence>
            <xs:element name="intents" type="intentsType"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="intentsType">
        <xs:sequence>
            <xs:element name="intent" type="intentType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="intentType">
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== Choinek/magento2-alexa/app/code/AlanKent/Alexa/etc/alexa/alexa_listeners.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:AlanKent_Alexa:etc/alexa/alexa_listeners.xsd">
    <alexaListener name="order_management" type="AlanKent\AlexaOrderManagement\App\OrderManagementAlexaApp">
        <intents>
            <intent value="ReportOrderCount"/>
            <intent value="FindNextOrder"/>
            <intent value="FirstOrderItem"/>
            <intent value="NextOrderItem"/>
            <intent value="MarkOrderAsDone"/>
        </intents>
    </alexaListener>
</config>
