=== Choinek/magento2-alexa/app/code/AlanKent/Alexa/etc/alexa/alexa_routers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alexaRouter" type="alexaRouterType" maxOccurs="unbounded" minOccurs="0">
                    <xs:unique name="alexaRouterName">
                        <xs:annotation>
                            <xs:documentation>
                                Alexa Listener name should be unique.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="alexaRouter"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="alexaRouterType">
        <xs:sequence>
            <xs:element name="intent" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="default" type="xs:boolean"/>
    </xs:complexType>
</xs:schema>

=== Choinek/magento2-alexa/app/code/AlanKent/AlexaOrderManagement/etc/alexa/alexa_routers.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:AlanKent_Alexa:etc/alexa/alexa_routers.xsd">
    <alexaRouter name="order_management" type="AlanKent\AlexaOrderManagement\App\OrderManagementAlexaApp" default="true">
        <intents>
            <intent>ReportOrderCount</intent>
            <intent>FindNextOrder</intent>
            <intent>FirstOrderItem</intent>
            <intent>NextOrderItem</intent>
            <intent>MarkOrderAsDone</intent>
        </intents>
    </alexaRouter>
</config>
